#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : procenv
Version  : 0.50
Release  : 12
URL      : https://github.com/jamesodhunt/procenv/archive/0.50.tar.gz
Source0  : https://github.com/jamesodhunt/procenv/archive/0.50.tar.gz
Summary  : Utility to show process environment
Group    : Development/Tools
License  : GPL-3.0 GPL-3.0+
Requires: procenv-bin
Requires: procenv-doc
BuildRequires : groff
BuildRequires : libcap-dev
BuildRequires : numactl-dev
BuildRequires : pkgconfig(check)

%description
This package contains a command-line tool that displays as much
detail about itself and its environment as possible. It can be
used as a test tool, to understand the type of environment a
process runs in, and for comparing system environments.

%package bin
Summary: bin components for the procenv package.
Group: Binaries

%description bin
bin components for the procenv package.


%package doc
Summary: doc components for the procenv package.
Group: Documentation

%description doc
doc components for the procenv package.


%prep
%setup -q -n procenv-0.50

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1508282398
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1508282398
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/procenv

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
